name: Run with QEMU VM
description: 'Run a command while a QEMU VM is running'
author: EtchDroid, Davide Depau

branding:
  icon: box
  color: orange

inputs:
  qemu-executable:
    description: Path to the QEMU executable
    required: false
    default: 'qemu-system-x86_64'
  video-record:
    description:
      Whether to enable Xvfb and record a video. You still need to enable the
      display output in the QEMU flags.
    required: false
    default: 'false'
  video-output:
    description: Path to the video output file
    required: false
    default: 'recording.mkv'
  video-resolution:
    description: Video recording resolution (virtual display resolution)
    required: false
    default: '1280x800'
  xbfb-screen:
    description: Xvfb screen number
    required: false
    default: '0'
  x11-display:
    description: X11 display number
    required: false
    default: ':95'
  cpu:
    description:
      Select CPU (run `qemu-system-x86_64 -cpu help` to see available CPUs)
    required: false
    default: 'host'
  enable-kvm:
    description: Whether to enable KVM
    required: false
    default: 'true'
  smp:
    description: Number of CPUs
    required: false
    default: '4'
  memory:
    description: Memory size in MB
    required: false
    default: '4096'
  kernel:
    description: Path to kernel image to boot, if booting a kernel directly
    required: false
    default: ''
  initrd:
    description: Path to initrd image to boot, if booting a kernel directly
    required: false
    default: ''
  cmdline:
    description: Kernel command line arguments, if booting a kernel directly
    required: false
    default: ''
  flags:
    description: Additional flags to pass to QEMU, newline-separated
    required: false
    default: ''
  run:
    description: Script to run in the VM
    required: true
  shell:
    description: Shell to use to run the script
    required: false
    default: 'bash'

outputs:
  run-id:
    description: The ID of the run
    value: ${{ steps.main.outputs.run-id }}
  ffmpeg-pid:
    description: The PID of the ffmpeg process, if video recording is enabled
    value: ${{ steps.main.outputs.ffmpeg-pid }}
  xvfb-pid:
    description: The PID of the Xvfb process, if video recording is enabled
    value: ${{ steps.main.outputs.xvfb-pid }}
  qemu-pid:
    description: The PID of the QEMU process
    value: ${{ steps.main.outputs.qemu-pid }}
  i3-pid:
    description: The PID of the i3 process, if video recording is enabled
    value: ${{ steps.main.outputs.i3-pid }}
  video-output:
    description: The path to the video output file
    value: ${{ steps.main.outputs.video-output }}

runs:
  using: composite
  steps:
    - name: Set up access to sibling actions
      shell: bash
      run: |
        ln -sf "$(realpath "$GITHUB_ACTION_PATH")" ./qemu-kvm-action

    - name: Set up dependencies
      uses: ./qemu-kvm-action/setup

    - name: Start QEMU
      id: main
      uses: ./qemu-kvm-action/start/
      with:
        qemu-executable: ${{ inputs.qemu-executable }}
        video-record: ${{ inputs.video-record }}
        video-output: ${{ inputs.video-output }}
        video-resolution: ${{ inputs.video-resolution }}
        xbfb-screen: ${{ inputs.xbfb-screen }}
        x11-display: ${{ inputs.x11-display }}
        cpu: ${{ inputs.cpu }}
        enable-kvm: ${{ inputs.enable-kvm }}
        smp: ${{ inputs.smp }}
        memory: ${{ inputs.memory }}
        kernel: ${{ inputs.kernel }}
        initrd: ${{ inputs.initrd }}
        cmdline: ${{ inputs.cmdline }}
        flags: ${{ inputs.flags }}

    - name: Run script
      shell: ${{ inputs.shell }}
      run: ${{ inputs.run }}

    - name: Stop QEMU
      uses: ./qemu-kvm-action/stop/
      with:
        run-id: ${{ steps.main.outputs.run-id }}
