name: Set up QEMU KVM Action
description: 'Install and cache APT dependencies for QEMU KVM'
author: EtchDroid, Davide Depau

inputs:
  video-record:
    description:
      Whether to install dependencies for video recording. Defaults to true,
      disable to save time if you don't need video recording.
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Disable man-db trigger
      shell: bash
      run: |
        echo 'set man-db/auto-update false' | sudo debconf-communicate >/dev/null
        sudo dpkg-reconfigure man-db

    - name: Install and cache APT dependencies
      uses: Eeems-Org/apt-cache-action@v1
      with:
        packages: |
          qemu-system-x86 qemu-utils ovmf ${{ inputs.video-record == 'true' && 'x11-utils ffmpeg libblas3 i3-wm qemu-system-gui qemu-system-modules-opengl' || '' }}
