on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/setup-nasm@v1

      - name: Prepare Boot-Man demo
        run: |
          git clone https://github.com/guyhill/Boot-Man
          cd Boot-Man
          make

      - name: Run QEMU
        id: run-qemu
        uses: ./
        with:
          video-record: true
          flags: 'Boot-Man/boot-man.bin'
          run: sleep 10

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: recording
          path: ${{ steps.run-qemu.outputs.video-output }}
